services:
  ai-service-docker:
    build:
      context: ./ai-service
    container_name: ai-service-docker
    env_file:
      - ./ai-service/.env
    volumes:
      - ./data:/app/data
    ports:
      - "5000:5000"
    restart: unless-stopped

  admin-panel-docker:
    build:
      context: ./admin-panel
    container_name: admin-panel-docker
    env_file:
      - ./admin-panel/.env
    volumes:
      - ./admin-panel:/app
      - ./data:/app/data
    ports:
      - "5001:5001"
    depends_on:
      - ai-service-docker
    restart: unless-stopped

  wa-gateway-docker:
    build:
      context: ./wa-gateway
    container_name: wa-gateway-docker
    env_file:
      - ./wa-gateway/.env
    volumes:
      - ./data:/app/data
    ports:
      - "3000:3000"
    restart: unless-stopped
